<html>
<head>
	<title>Address Book | All Records</title>
<%
if Session("user") = "" then
	response.redirect("login.asp?m=session expired or direct access")
end if
%>
</head>
<body><center>
<!-- #include file="header.inc" -->


<%
' Create connection and get a set of records
set conn = Server.CreateObject("ADODB.Connection")
conn.Open "addressbookdsn"

set rs = Server.CreateObject("ADODB.RecordSet")
rs.Open "SELECT id, contact_name, phone FROM detail", conn
%>

<h3>Following is the data currently in the database</h3>
<table border="1" width="40%" align="center">
	<tr>
		<th>Name</th>
		<th>Phone</th>
		<th>Action</th>
	</tr>
	<!-- 
		The following code runs a loop. Whatever is in the <% %> will be replaced by html generated by IIS and the ASP engine. So here, in the <td> elements,all that ASP code will be replaced by the value in each column (or field) of the table.

	In the last td, the user will have a link to the update and delete page. The id of the row to be updated or deleted is sent to the update or delete page in the query string.
	-->
	<% do until rs.eof  %>
	<tr>
		<td><%=rs.fields.item("contact_name").value%></td>
		<td><%=rs.fields.item("phone").value%></td>
		<td align="center">
			<a href="update.asp?id=<%=rs.fields.item("id").value%>&a=update">
				Update
			</a>
			&nbsp;&nbsp;&nbsp;&nbsp;
			<a href="delete.asp?id=<%=rs.fields.item("id").value%>&a=delete">
				Delete
			</a>
		</td>
	<%rs.movenext%>
	</tr>
	<%
		' End of do until loop
		loop
		' Close connections
		rs.close
		conn.close
	%>
</table>
<!-- #include file="footer.inc" -->
</center>
</body>
</html>		
