CREATE TABLE DEPT
(
    DEPT_NO INT PRIMARY KEY,
    DNAME VARCHAR2(30), 
    LOC VARCHAR2(30)
);

CREATE TABLE EMP
(
    EMP_ID INT PRIMARY KEY,
    NAME VARCHAR(30),
    CITY VARCHAR(30),
    JOB VARCHAR(30),
    SALARY INT,
    JOIN_DATE DATE,
    COMMISSION INT,
    DEPT_NO INT REFERENCES DEPT(DEPT_NO)
);